### ISSUE TITLE
Please Compatible for PMMP 1.4.0

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ChatCensor#15]
The censor is not working. Some functions are down. Please fix.

**Comment by Flavius12** [comment]
Which API version do you mean?

**Comment by ghost** [comment]
3.0.1

**Comment by Flavius12** [comment]
Can you be more precise about the bugs you found?

**Comment by ghost** [comment]
Words not replace, anti spam doesnt work, anti caps doesnt work, anti ad doesnt work. There are no errors in the console. Most things do not work. Please check all functions. Plugin test on pmmp API 3.0.1 please.

**Comment by Flavius12** [comment]
I don't find any information about PMMP API 3.0.1. The latest PMMP API version I know is 3.0.0-ALPHA12

**Comment by ghost** [comment]
https://github.com/TuranicTeam/Altay

**Comment by Flavius12** [comment]
I'm sorry but PMMP forks are not supported and they will never be supported. Please report bugs only if you are using the plugin with the official PMMP software.
