### ISSUE TITLE
The use of the section sign

### ISSUE THREAD

**Issue by PEMapModder** [EvolSoft/ChatCensor#5]
Plugins should use constants in the `TextFormat` class instead of hardcoding the color sign. They may be deprecated in MCPE in the future.

**Comment by Flavius12** [comment]
Where in this code?

**Comment by PEMapModder** [comment]
The uses of `Main::translateColor`.

I mean not only the `TextFormat::ESCAPE` character is changed. According to @shoghicp, a markup-style system is being worked on.

**Comment by Flavius12** [comment]
Ah ok. Thank you for report. So how will we able to write formatted messages? Do you have a preview of the new markup style?

**Comment by ifvictr** [comment]
@Flavius12 Formatted messages? Like the `&<text-format-code-here>` you're using? As long as you use the constants from `\pocketmine\utils\TextFormat`, it should be fine. You shouldn't use `§` directly, like @PEMapModder said, it would/could change. But I can't find this "markup-style-system" in any of the branches. .-.

**Comment by Flavius12** [comment]
@Gamecrafter the main goal of the translateColors function is to prevent the use of § symbol written directly on messages. Then it was made also because there was a bug which didn't print colored messages correctly when using § in strings

**Comment by PEMapModder** [comment]
@Gamecrafter it is something new, or probably working in progress, probably somewhere hidden in MCPE, or somewhere in Shoghi's personal branch of MCPE source. It is nowhere public yet. But Shoghi mentioned about the plan to do so.
BTW, the markup style I meant may not really be markup, but probably JSON, etc.
