### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ChatCensor#8]
1)Make block caps: RU and EN

2)Block words, caps in /me and /tell

3)Inform administrators about violations

4)blocking swear words and caps on the sign

**Comment by Pub4Game** [comment]
Block words in /me and /tell

**Comment by Pub4Game** [comment]
Inform administrators about violations

**Comment by Pub4Game** [comment]
blocking swear words and caps on the plates on the sign

**Comment by Pub4Game** [comment]
@Flavius12 
You also will not have enough time?(( 

Make 2, please

**Comment by Flavius12** [comment]
I don't know. I don't have enough time. Keep in mind that these plugin updates may be released on December

**Comment by Pub4Game** [comment]
Wooo as it is long...... Make ChatCensor first, I very need it, thanks

**Comment by Flavius12** [comment]
All updates will be released at the same time

**Comment by Pub4Game** [comment]
@Flavius12 Add anti advertising :D

**Comment by Flavius12** [comment]
You can block words which can contain urls, compamy names, ...

**Comment by Pub4Game** [comment]
I mean not only words, but also ip 123.123.123.123 19132

**Comment by Flavius12** [comment]
Yes of course

**Comment by Pub4Game** [comment]
When you have the time to update this plugin? He now really need

**Comment by Flavius12** [comment]
This summer maybe

**Comment by Pub4Game** [comment]
omg
