### ISSUE TITLE
Not blocked words

### ISSUE THREAD

**Issue by Pub4Game** [EvolSoft/ChatCensor#9]
Not blocked words containing digits 

24minecraft.net

Used the command:

/addblock 24minecraft

**Comment by Flavius12** [comment]
Thank you for report :+1: 
I'll rewrite the word censor engine and I'll add the dots support

**Comment by Pub4Game** [comment]
@Flavius12 !?

**Comment by Flavius12** [comment]
What?

**Comment by Pub4Game** [comment]
When will be update?

**Comment by Flavius12** [comment]
When I have a bit of free time. I'm very busy with school and I'm writing an Operating System and unfortunately this takes my bit of free time

**Comment by Flavius12** [comment]
Fixed in v2.0
